[IA64] trivial compilation fix caused by c/s 17847:8a0415fac759.
This patch fixes the following compilation error caused
by c/s 17847:8a0415fac759.

machine_kexec.c: In function 'arch_crash_save_vmcoreinfo':
machine_kexec.c:201: error: 'frametable_pg_dir' undeclared (first use in this function)
machine_kexec.c:201: error: (Each undeclared identifier is reported only once
machine_kexec.c:201: error: for each function it appears in.)

Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>